def menu_biblioteca():
    print("\n GERENCIADOR DE BIBLIOTECA ")
    print("1. Cadastrar uma nova biblioteca")
    print("2. Alterar nome da biblioteca")
    print("3. Excluir uma biblioteca")
    print("4. Listar bibliotecas")
    print("5. Cadastrar um novo livro")
    print("6. Alterar dados de um livro")
    print("7. Excluir um livro")
    print("8. Listar livros")
    print("9. Adicionar livro à biblioteca")
    print("10. Remover livro de uma biblioteca")
    print("11. Listar livros cadastrados em uma biblioteca")
    print("12. Alterar status de um livro em uma biblioteca")
    print("13. Buscar livro")
    print("14. Sair")
